version: '2'

services:
    device-kiwi-prugw:
        image: openkorp/openkorp-device-bbblue-prugw-multi:latest
        network_mode: "host"
        privileged: true
        volumes:
            - /sys/:/sys/
        command: "/usr/bin/opendlv-device-kiwi-prugw \
                --cid=${CID} \
                --names=${NAMES} \
                --types=${TYPES} \
                --channels=${CHANNELS} \
                --offsets=${OFFSETS} \
                --maxvals=${MAXVALS} \
                --verbose=0"
